quarkus:
  http:
    port: 8080
  log:
    level: debug
    console:
      json: false
#        zone-id: GMT+8
#        date-format: 'yyyy-MM-dd HH:mm:ss.SSS'
#        exception-output-type: formatted
    category:
      "io.quarkus":
        level: INFO

  datasource:
    db-kind: postgresql
    devservices:
      enabled: true
  hibernate-orm:
    database:
      generation: drop-and-create

config:
  greeting:
    message: local-hello11

service:
  config:
    api:
      url: http//localhost
      apiKey: xx
      secret: yy
      connectTimeout: 5000
      socketTimeout: 15000
      retry:
        delay: 5000
        maxDelay: 10000
        multiplier: 3
        maxAttempts: 1